server:
    #port: 8082
    context-path: /ui
    session:
      cookie:
        name: UISESSION
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://spring-security-sso-auth-server-sso-auth-server.origin.cloudmaf.io/auth/oauth/token
      userAuthorizationUri: http://spring-security-sso-auth-server-sso-auth-server.origin.cloudmaf.io/auth/oauth/authorize
    resource:
      userInfoUri: http://spring-security-sso-auth-server-sso-auth-server.origin.cloudmaf.io/auth/user/me
spring:
  thymeleaf:
    cache: false  
